### ISSUE TITLE
The bottom emoji breaks rust-analyzer

### ISSUE THREAD

**Issue by jasikpark** [fasterthanlime/feedback#169]
I found something wrong on this page:

  https://fasterthanli.me/articles/the-bottom-emoji-breaks-rust-analyzer#position=33.9

https://fasterthanli.me/articles/the-bottom-emoji-breaks-rust-analyzer#what-is-a-character:~:text=And%20so%2C-,%22%F0%A0%80%80,-%22%20is%3A

  Here's what it is:

![A3D49AAF-C1BF-4609-A96D-AA268FDC3B77](https://user-images.githubusercontent.com/10626596/218767914-6d40596b-0c3a-41a9-aa8a-e1982214dd0f.png)

missing font shows a tofu character, maybe that was intentional, but i don’t think it was?

**Comment by fasterthanlime** [comment]
This is what it renders like on Chrome for Windows 11:

<img width="331" alt="image" src="https://user-images.githubusercontent.com/7998310/218791484-4344d9ed-af0f-426f-b27b-12ce229f98da.png">

I'm afraid the blame lies with whichever mobile browser you're using.

**Comment by jasikpark** [comment]
safari on ios

**Comment by jasikpark** [comment]
<img width="714" alt="image" src="https://user-images.githubusercontent.com/10626596/218804732-6d11aa07-9958-4ca7-bb7d-eca8de33cded.png">
Arc (chromium) on macOS

I think maybe the fonts that Windows ship with that `serif` falls back to includes that? and iOS / macOS don't?

**Comment by fasterthanlime** [comment]
> I think maybe the fonts that Windows ship with that `serif` falls back to includes that? and iOS / macOS don't?

Maybe!

> It seems that the base Source Serif Pro doesn't include that CJK character?

Sure, but you'd imagine it's smart enough to fall back to something else?

**Comment by fasterthanlime** [comment]
Okay, I've deployed an inline image for it so you should see at least the second one of these:

<img width="343" alt="image" src="https://user-images.githubusercontent.com/7998310/218806848-ba12cef7-6225-4e47-bb2e-ac2f35008358.png">

**Comment by jasikpark** [comment]
If you use unicode-ranges (sorry if you've already fiddled with this 😓)

```css
/* cyrillic-ext */
@font-face {
  font-family: 'Inter';
  font-style: normal;
  font-weight: 200 900;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/inter/v12/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa2JL7W0Q5n-wU.woff2) format('woff2');
  unicode-range: U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F;
}
/* cyrillic */
@font-face {
  font-family: 'Inter';
  font-style: normal;
  font-weight: 200 900;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/inter/v12/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa0ZL7W0Q5n-wU.woff2) format('woff2');
  unicode-range: U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116;
}
/* greek-ext */
@font-face {
  font-family: 'Inter';
  font-style: normal;
  font-weight: 200 900;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/inter/v12/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa2ZL7W0Q5n-wU.woff2) format('woff2');
  unicode-range: U+1F00-1FFF;
}
/* greek */
@font-face {
  font-family: 'Inter';
  font-style: normal;
  font-weight: 200 900;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/inter/v12/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa1pL7W0Q5n-wU.woff2) format('woff2');
  unicode-range: U+0370-03FF;
}
/* vietnamese */
@font-face {
  font-family: 'Inter';
  font-style: normal;
  font-weight: 200 900;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/inter/v12/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa2pL7W0Q5n-wU.woff2) format('woff2');
  unicode-range: U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB;
}
/* latin-ext */
@font-face {
  font-family: 'Inter';
  font-style: normal;
  font-weight: 200 900;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/inter/v12/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa25L7W0Q5n-wU.woff2) format('woff2');
  unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
}
/* latin */
@font-face {
  font-family: 'Inter';
  font-style: normal;
  font-weight: 200 900;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/inter/v12/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa1ZL7W0Q5nw.woff2) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}

```

You should be able to prevent extraneous Source Serif Pro languages from being loaded unless they are required by the page

Especially nice for one-off headers where you just want like 5 characters lol
